

export const imageGallery = [{
    id:"1",
    name: "12A.jpg",
    description: "Grade 12A",
    category: "class-photo",
    year: "2022",
}, {
    id:"2",
    name: "12B.jpg",
    description: "Grade 12B",
    category: "class-photo",
    year: "2022",
}, {
    id:"3",
    name: "12C.jpg",
    description: "Grade 12C",
    category: "class-photo",
    year: "2022",
}, {
    id:"4",
    name: "12D.jpg",
    description: "Grade 12D",
    category: "class-photo",
    year: "2022",
}, {
    id:"5",
    name: "12E.jpg",
    description: "Grade 12E",
    category: "class-photo",
    year: "2022",
}, {
    id:"6",
    name: "12F.jpg",
    description: "Grade 12F",
    category: "class-photo",
    year: "2022",
}, {
    id:"7",
    name: "11A.jpg",
    description: "Grade 11A",
    category: "class-photo",
    year: "2022",
}, {
    id:"8",
    name: "11B.jpg",
    description: "Grade 11B",
    category: "class-photo",
    year: "2022",
}, {
    id:"9",
    name: "11C.jpg",
    description: "Grade 11C",
    category: "class-photo",
    year: "2022",
}, {
    id:"10",
    name: "11D.jpg",
    description: "Grade 11D",
    category: "class-photo",
    year: "2022",
}, {
    id:"11",
    name: "11E.jpg",
    description: "Grade 11E",
    category: "class-photo",
    year: "2022",
}, {
    id:"12",
    name: "10A.jpg",
    description: "Grade 10A",
    category: "class-photo",
    year: "2022",
}, {
    id:"13",
    name: "10C.jpg",
    description: "Grade 10C",
    category: "class-photo",
    year: "2022",
}, {
    id:"14",
    name: "9B.jpg",
    description: "Grade 9B",
    category: "class-photo",
    year: "2022",
}, {
    id:"15",
    name: "9C.jpg",
    description: "Grade 9C",
    category: "class-photo",
    year: "2022",
}, {
    id:"16",
    name: "9D.jpg",
    description: "Grade 9D",
    category: "class-photo",
    year: "2022",
}, {
    id:"17",
    name: "8A.jpg",
    description: "Grade 8A",
    category: "class-photo",
    year: "2022",
}, {
    id:"18",
    name: "8B.jpg",
    description: "Grade 8B",
    category: "class-photo",
    year: "2022",
}, {
    id:"19",
    name: "8C.jpg",
    description: "Grade 8C",
    category: "class-photo",
    year: "2022",
}, {
    id:"20",
    name: "8D.jpg",
    description: "Grade 8D",
    category: "class-photo",
    year: "2022",
}, {
    id:"21",
    name: "8E.jpg",
    description: "Grade 8E",
    category: "class-photo",
    year: "2022",
}, {
    id:"23",
    name: "gr9-debate-team.jpeg",
    description: "Grade 9 Debate team",
    category: "other",
    year: "2022",
}, {
    id:"24",
    name: "interhouse-athletics.jpeg",
    description: "Interhouse Athletics",
    category: "sport",
    year: "2022",
}, {
    id:"25",
    name: "netball.jpg",
    description: "Netball",
    category: "sport",
    year: "2022",
}, {
    id:"26",
    name: "rugby.jpg",
    description: "Rugby",
    category: "other",
    year: "2022",
}, {
    id:"27",
    name: "soccer.jpg",
    description: "Soccer",
    category: "sport",
    year: "2022",
}, {
    id:"28",
    name: "staff01.jpg",
    description: "Our Staff",
    category: "staff",
    year: "2022",
}, {
    id:"29",
    name: "staff02.jpg",
    description: "Our Staff",
    category: "staff",
    year: "2022",
}, {
    id:"30",
    name: "staff03.jpg",
    description: "Our Staff",
    category: "staff",
    year: "2022",
}, {
    id:"22",
    name: "culture.jpg",
    description: "Culture",
    category: "other",
    year: "2022",
}, {
    id:"31",
    name: "prom01-2015.jpg",
    description: "Prom",
    category: "prom",
    year: "2015",
}, {
    id:"32",
    name: "prom02-2015.jpg",
    description: "Prom",
    category: "prom",
    year: "2015",
}, {
    id:"33",
    name: "prom03-2015.jpg",
    description: "Prom",
    category: "prom",
    year: "2015",
}, {
    id:"34",
    name: "prom04-2015.jpg",
    description: "Prom",
    category: "prom",
    year: "2015",
}, {
    id:"35",
    name: "prom05-2015.jpg",
    description: "Prom",
    category: "prom",
    year: "2015",
}, {
    id:"36",
    name: "prom06-2015.jpg",
    description: "Prom",
    category: "prom",
    year: "2015",
},
]