
export const papers = [{
    id: 1,
    name: "Accounting",
    p1: "/papers/accounting/accounting-P1-nov-2023.pdf",
    p1memo: "/papers/accounting/accounting-P1-memo-nov-2023.pdf",
    p2: "/papers/accounting/accounting-P1-nov-2023.pdf",
    p2memo: "/papers/accounting/accounting-P2-memo-nov-2023.pdf",
}, {
    id: 2,
    name: "Agricultural Sciences",
    p1: "/papers/agriculture/agriculture-P1-nov-2023.pdf",
    p1memo: "/papers/agriculture/agriculture-P1-memo-nov-2023.pdf",
    p2: "/papers/agriculture/agriculture-P2-nov-2023.pdf",
    p2memo: "/papers/agriculture/agriculture-P2-memo-nov-2023.pdf",
}, {
    id: 3,
    name: "Economics",
    p1: "/papers/economics/economics-P1-nov-2023.pdf",
    p1memo: "/papers/economics/economics-P1-memo-nov-2023.pdf",
    p2: "/papers/economics/economics-P2-nov-2023.pdf",
    p2memo: "/papers/economics/economics-P2-memo-nov-2023.pdf",
}, {
    id: 4,
    name: "Geography",
    p1: "/papers/geography/geography-P1-nov-2023.pdf",
    p1memo: "/papers/geography/geography-P1-memo-nov-2023.pdf",
    p2: "/papers/geography/geography-P2-nov-2023.pdf",
    p2memo: "/papers/geography/geography-P2-memo-nov-2023.pdf",
}, {
    id: 5,
    name: "History",
    p1: "/papers/history/history-P1-nov-2023.pdf",
    p1memo: "/papers/history/history-P1-memo-nov-2023.pdf",
    p2: "/papers/history/history-P2-nov-2023.pdf",
    p2memo: "/papers/history/history-P2-memo-nov-2023.pdf",
}, {
    id: 6,
    name: "Life Sciences",
    p1: "/papers/life-sciences/biology-P1-nov-2023.pdf",
    p1memo: "/papers/life-sciences/biology-P1-memo-nov-2023.pdf",
    p2: "/papers/life-sciences/biology-P2-nov-2023.pdf",
    p2memo: "/papers/life-sciences/biology-P2-memo-nov-2023.pdf",
}, {
    id: 7,
    name: "Mathematical Literacy",
    p1: "/papers/maths-lit/maths-lit-P1-nov-2023.pdf",
    p1memo: "/papers/maths-lit/maths-lit-P1-memo-nov-2023.pdf",
    p2: "/papers/maths-lit/maths-lit-P2-nov-2023.pdf",
    p2memo: "/papers/maths-lit/maths-lit-P2-memo-nov-2023.pdf",
}, {
    id: 8,
    name: "Mathematics",
    p1: "/papers/mathematics/math-P1-nov-2023.pdf",
    p1memo: "/papers/mathematics/math-P1-memo-nov-2023.pdf",
    p2: "/papers/mathematics/maths-P2-nov-2023.pdf",
    p2memo: "/papers/mathematics/maths-P2-memo-nov-2023.pdf",
}, {
    id: 9,
    name: "Physical Sciences",
    p1: "/papers/physical-sciences/physics-nov-2023.pdf",
    p1memo: "/papers/physical-sciences/physics-memo-nov-2023.pdf",
    p2: "/papers/physical-sciences/chemistry-nov-2023.pdf",
    p2memo: "/papers/physical-sciences/chemistry-memo-nov-2023.pdf",
}, {
    id: 10,
    name: "Tourism",
    p1: "/papers/tourism/tourism-nov-2023.pdf",
    p1memo: "/papers/tourism/tourism-memo-nov-2023.pdf",
    p2: "/papers/tourism/tourism-nov-2023.pdf",
    p2memo: "/papers/tourism/tourism-memo-nov-2023.pdf",
},

]